# TODO: Replace the 'from' URL below with your Netlify site URL
[[redirects]]
  from = "https://teal-truffle-c790a7.netlify.app/*"
  to = "https://wrightwaycleanid.com/:splat"
  status = 301
  force = true
